
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: css
  style: expanded


###
# try jekyll-redirect-from gem
gems:
  - jekyll-redirect-from


exclude:
  - README.md


safe: true
lsi: false
